"""add reading progress

Revision ID: 3e66512bc8bf
Revises: 610d9e00b432
Create Date: 2026-05-07 14:31:26.707149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e66512bc8bf'
down_revision = '610d9e00b432'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pages', sa.Integer(), nullable=True))

    with op.batch_alter_table('shelf_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_page', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shelf_item', schema=None) as batch_op:
        batch_op.drop_column('current_page')

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('pages')

    # ### end Alembic commands ###
