"""fix comment session_id

Revision ID: 3ef4c8c85cf4
Revises: 9992bf532ae4
Create Date: 2026-05-05 15:40:15.924236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ef4c8c85cf4'
down_revision = '9992bf532ae4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.String(length=120), nullable=True))

    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.drop_column('session_id')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('session_id')

    # ### end Alembic commands ###
