"""Add review editing support

Revision ID: 7714c2f9b259
Revises: 6a1ee96c54fa
Create Date: 2026-05-13 12:35:32.251432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7714c2f9b259'
down_revision = '6a1ee96c54fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.create_unique_constraint('unique_user_book_review', ['user_id', 'book_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_book_review', type_='unique')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
