"""Add new book columns from API

Revision ID: 832bac3df22b
Revises: 3e66512bc8bf
Create Date: 2026-05-08 16:45:37.971764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '832bac3df22b'
down_revision = '3e66512bc8bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('openlibrary_id', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('page_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('publish_year', sa.Integer(), nullable=True))
        batch_op.drop_column('pages')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pages', sa.INTEGER(), nullable=True))
        batch_op.drop_column('publish_year')
        batch_op.drop_column('page_count')
        batch_op.drop_column('openlibrary_id')

    # ### end Alembic commands ###
