"""Add want to read model

Revision ID: 9992bf532ae4
Revises: bb4c8adf2e52
Create Date: 2026-05-02 23:06:17.212227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9992bf532ae4'
down_revision = 'bb4c8adf2e52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('want_to_read',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'session_id', name='unique_book_session_want_to_read')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('want_to_read')
    # ### end Alembic commands ###
